"""empty message

Revision ID: 03fd9e338ecd
Revises: f82131ea7641
Create Date: 2023-11-13 17:04:20.806073

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "03fd9e338ecd"
down_revision: Union[str, None] = "f82131ea7641"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
