"""empty message

Revision ID: f82131ea7641
Revises: 4761b2ba7ed4
Create Date: 2023-11-13 17:03:05.621790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82131ea7641'
down_revision: Union[str, None] = '4761b2ba7ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type_item_id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('recycling_nuggets', sa.FLOAT(), nullable=False),
    sa.Column('rune_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['rune_id'], ['rune.id'], name='fk_item_rune'),
    sa.ForeignKeyConstraint(['type_item_id'], ['type_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
